/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SoliasButton {
        /**
          * Button Label
         */
        "label": string;
        /**
          * Button custom class
         */
        "styleClass": string;
    }
}
declare global {
    interface HTMLSoliasButtonElement extends Components.SoliasButton, HTMLStencilElement {
    }
    var HTMLSoliasButtonElement: {
        prototype: HTMLSoliasButtonElement;
        new (): HTMLSoliasButtonElement;
    };
    interface HTMLElementTagNameMap {
        "solias-button": HTMLSoliasButtonElement;
    }
}
declare namespace LocalJSX {
    interface SoliasButton {
        /**
          * Button Label
         */
        "label"?: string;
        /**
          * Button custom class
         */
        "styleClass"?: string;
    }
    interface IntrinsicElements {
        "solias-button": SoliasButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "solias-button": LocalJSX.SoliasButton & JSXBase.HTMLAttributes<HTMLSoliasButtonElement>;
        }
    }
}
