/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SoliasBarchart {
    }
}
declare global {
    interface HTMLSoliasBarchartElement extends Components.SoliasBarchart, HTMLStencilElement {
    }
    var HTMLSoliasBarchartElement: {
        prototype: HTMLSoliasBarchartElement;
        new (): HTMLSoliasBarchartElement;
    };
    interface HTMLElementTagNameMap {
        "solias-barchart": HTMLSoliasBarchartElement;
    }
}
declare namespace LocalJSX {
    interface SoliasBarchart {
    }
    interface IntrinsicElements {
        "solias-barchart": SoliasBarchart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "solias-barchart": LocalJSX.SoliasBarchart & JSXBase.HTMLAttributes<HTMLSoliasBarchartElement>;
        }
    }
}
