/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SoliasChartOptions, SoliasDefaultChartData } from "./types";
export { SoliasChartOptions, SoliasDefaultChartData } from "./types";
export namespace Components {
    interface SoliasBarchart {
        /**
          * Input data
         */
        "data": SoliasDefaultChartData;
        /**
          * Chart Options
         */
        "options": SoliasChartOptions;
    }
}
declare global {
    interface HTMLSoliasBarchartElement extends Components.SoliasBarchart, HTMLStencilElement {
    }
    var HTMLSoliasBarchartElement: {
        prototype: HTMLSoliasBarchartElement;
        new (): HTMLSoliasBarchartElement;
    };
    interface HTMLElementTagNameMap {
        "solias-barchart": HTMLSoliasBarchartElement;
    }
}
declare namespace LocalJSX {
    interface SoliasBarchart {
        /**
          * Input data
         */
        "data"?: SoliasDefaultChartData;
        /**
          * Chart Options
         */
        "options"?: SoliasChartOptions;
    }
    interface IntrinsicElements {
        "solias-barchart": SoliasBarchart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "solias-barchart": LocalJSX.SoliasBarchart & JSXBase.HTMLAttributes<HTMLSoliasBarchartElement>;
        }
    }
}
